### ISSUE TITLE
US: Ziehen von Wartenummern

### ISSUE THREAD

**Issue by normanmerten** [methodpark/digitaleswarten#1]
Ich als Patient kann mir digital eine Wartezimmernummer "ziehen", um erst zu der Behandlung vor Ort zu sein.

**Comment by maxrohleder** [comment]
Edit: Wartenummer wird von Praxis zugewiesen. Patient kann den Status seiner Wartenummer über eine ID auf einer Website abrufen á la Einwohnermeldeamt (V1).

**Comment by maxrohleder** [comment]
Zweite Version wäre über Notifications. Optional mit estimated Wartezeit.
